"""empty message

Revision ID: 7f47c2a2eab5
Revises: 
Create Date: 2025-06-09 15:03:19.797485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f47c2a2eab5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_category', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=16),
               existing_comment='经度',
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=16),
               existing_comment='纬度',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_category', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.String(length=16),
               type_=mysql.FLOAT(),
               existing_comment='纬度',
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.String(length=16),
               type_=mysql.FLOAT(),
               existing_comment='经度',
               existing_nullable=True)

    # ### end Alembic commands ###
